### ISSUE TITLE
Documentation: Review metric description

### ISSUE THREAD

**Issue by dgarijo** [oeg-upm/fair_ontologies#135]
We should follow the template here: https://github.com/FAIRMetrics/Metrics/blob/master/MaturityIndicators/Gen2/Gen2_MI_A1.1.md#what-is-being-measured

For each metric

**Comment by juanjemdIos** [comment]
is quite diferent. Do you suggest to follow the ttl, how to show the information or both?. Could be a merge between this and our curren ttl?

**Comment by dgarijo** [comment]
The metric description in the trl should follow that template
